from playwright.sync_api import Page, expect

def test_blaze_order(page: Page):
    page.goto("https://www.demoblaze.com/")
    expect(page.locator("#tbodyid")).to_contain_text("Samsung galaxy s6")
    page.locator(".card > a").first.click()
    expect(page.get_by_text("Product description")).to_be_visible()
    expect(page.get_by_role("link", name="Add to cart")).to_be_visible()
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.get_by_role("link", name="Add to cart").click()
    page.get_by_role("link", name="Cart", exact=True).click()
    expect(page.get_by_role("cell", name="Samsung galaxy s6")).to_be_visible()
    page.get_by_role("cell", name="360").click()
    page.get_by_role("heading", name="Total").click()
    page.get_by_role("button", name="Place Order").click()
    expect(page.get_by_role("heading", name="Place order")).to_be_visible()
    expect(page.get_by_label("Total:")).to_be_visible()
    page.locator('#name').is_visible()
    page.click('#name')
    page.locator('#name').fill('Test')
    page.click('#country')
    page.locator('#country').fill('Canada')
    page.click('#city')
    page.locator('#city').fill('Winnipeg')
    page.click('#card')
    page.locator('#card').fill('4111111111111111')
    page.click('#month')
    page.locator('#month').fill('April')
    page.click('#year')
    page.locator('#year').fill('2029')
    expect(page.get_by_role("button", name="Purchase")).to_be_visible()
    page.get_by_role("button", name="Purchase").click()
    page.get_by_role("heading", name="Thank you for your purchase!").click()
    expect(page.get_by_role("heading", name="Thank you for your purchase!")).to_be_visible()
    expect(page.get_by_role("button", name="OK")).to_be_visible()
    page.get_by_role("button", name="OK").click()
